name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - run: npm ci
            - run: npm test

    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - run: npm ci
            - run: npm test
